mymain.out: mymathfunc.o mystrfunc.o mymain.o
	gcc -o mymain.out mymain.o mymathfunc.o mystrfunc.o

mymain.o: mymain.c
	gcc -c mymain.c

mymathfunc.o: mymathfunc.c
	gcc -c mymathfunc.c

mystrfunc.o : mystrfunc.c
	gcc -c mystrfunc.c

