#!/bin/bash



if [ $# -gt 0 ]
then
	if [  $# -gt 6  ]
	then
		echo "arguments are greqater than 6"
	
	
	elif [ $# -eq 1 ]
	then
		for i in `seq 1 10`
		do
			echo "`expr $1 \* $i`"
		done
	

	elif [ $# -eq 3 ]
	then
		if [ $2 = "-s"  ]
		then
			for i in `seq $3 10`
			do
			echo `expr $1 \* $i`
			done
		elif [ $2 = "-e"  ]
			then
				for i in `seq 1 $3`
				do
				echo `expr $1 \* $i`
			done
		fi
		

	

	elif [ $# -eq 5 ]
	then
		if [ $2 = "-s" -a $4 = "-e"  ]
		then
			for i in `seq $3 $5`
			do
			echo `expr $1 \* $i`
			done
		fi
	

	elif [ $# -eq 6 ]
	then
		if [ $2 = "-s" -a $4 = "-e" -a $6 = "-r"  ]
		then
			for i in `seq $5 -1 $3`
			do
			echo `expr $1 \* $i`
			done
		fi
	else
	
		echo "error"
	fi

else
	echo "no arguments are entered"
fi 
